# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - eternal
  - nostalebot
# Label to use when marking an issue as stale
staleLabel: wontfix
# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 1
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  Hi Friend,

  We really appreciate the time you have taken to open this issue/PR.
  OMAS only exists because people like you donate their time to its community.

  In an effort to maintain the repository we close threads that are inactive for more than 67 days.
  This thread will remain open for another 7 days, and then will be closed.

  If you'd like to keep it open, please comment/push and we will be happy to oblige :)
  Thank you again for contributing to this community effort!
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
